### PR TITLE
Brought module up-to-date with WorldBuilder API engine changes (e71090a, May 14)

### PR DESCRIPTION
**Pull request by prestidigitator**

### CODE REVIEW

**Comment by prestidigitator** [comment]
Oops.  This doesn't seem to be enough.  Crashes with a bunch of NullPointerExceptions still.  Should the engine be fixed so WorldBuilder sets the seed for all new providers added?  Hmm.  Checking the engine change again.

**Comment by prestidigitator** [comment]
Yes.  See [engine PR #1746](https://github.com/MovingBlocks/Terasology/pull/1746).

**Comment by msteiger** [comment]
Does the actual game crash for you or just the preview? The preview doesn't work yet, since the world generator tries to load a few things from `CoreRegistry` that are not defined in the minimal environment the preview screen sets up.

**Comment by prestidigitator** [comment]
It wouldn't compile.  Engine commit 7562c7a removed the non-default constructor for WorldBuilder, so it no longer takes a (long) seed parameter.  Actually it would probably make sense to add that constructor back even though setSeed() can now change the seed after the fact.  That would remove the need for this change.  Want me to add the constructor (and an explicit default constructor) back over in [engine PR #1746](https://github.com/MovingBlocks/Terasology/pull/1746) instead?

**Comment by msteiger** [comment]
Do you need to set the seed before you add the providers? It would be great if it worked the other way round (e.g. the preview screen changes the seed value at any time).

**Comment by prestidigitator** [comment]
With that engine change, it can now be done in either order or even interspersed.  In the first commit I was just trying to mimic the original API call order from when it was done in the constructor, and I did it before submitting the other PR.  Here's another commit with the order fixed up so it's closer to the original code.

**Comment by Cervator** [comment]
The engine PR was merged a little ways back, do we merge this now, does it need further tweaks, or does the engine change obsolete it or anything?

**Pull request merged**
